import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Challenge } from '../types';

interface Props {
  challenge: Challenge;
  highlight?: boolean;
}

const GeneratedChallengeCard: React.FC<Props> = ({ challenge, highlight = false }) => {
  const navigate = useNavigate();

  const handleStart = () => {
    navigate(`/challenges/${challenge.id}`);
  };

  const difficultyLabel = challenge.difficulty.charAt(0).toUpperCase() + challenge.difficulty.slice(1);

  return (
    <div
      className={`card h-full flex flex-col justify-between ${
        highlight ? 'ring-2 ring-primary-500 ring-offset-2 ring-offset-background' : ''
      }`}
    >
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white line-clamp-2">
            {challenge.title}
          </h3>
          <span className="inline-flex items-center rounded-full bg-primary-50 dark:bg-primary-900/30 px-3 py-1 text-xs font-medium text-primary-700 dark:text-primary-300">
            {difficultyLabel}
          </span>
        </div>

        <p className="text-sm text-gray-600 dark:text-gray-400 line-clamp-4">
          {challenge.description}
        </p>

        <div className="mt-2 grid grid-cols-2 gap-2 text-xs text-gray-500 dark:text-gray-400">
          <div>
            <span className="font-medium text-gray-700 dark:text-gray-300">Category:</span>{' '}
            {challenge.category?.name || 'Custom'}
          </div>
          <div>
            <span className="font-medium text-gray-700 dark:text-gray-300">XP:</span>{' '}
            {challenge.points}
          </div>
          <div>
            <span className="font-medium text-gray-700 dark:text-gray-300">Flag format:</span>{' '}
            flag&#123;...&#125;
          </div>
          {challenge.files_url && (
            <div>
              <span className="font-medium text-gray-700 dark:text-gray-300">Attachment:</span>{' '}
              <a
                href={challenge.files_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary-600 dark:text-primary-400 hover:underline"
              >
                Download file
              </a>
            </div>
          )}
        </div>
      </div>

      <div className="mt-4 flex items-center justify-between pt-4 border-t border-gray-200 dark:border-gray-700">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          Generated by AI • Saved to your library
        </p>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleStart}
            className="inline-flex items-center px-3 py-1.5 border border-transparent text-xs font-medium rounded-md shadow-sm text-white bg-primary-600 hover:bg-primary-700"
          >
            Start Challenge
          </button>
        </div>
      </div>
    </div>
  );
};

export default GeneratedChallengeCard;


