import React from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  ShieldCheckIcon,
  AcademicCapIcon,
  TrophyIcon,
  ChartBarIcon,
  SparklesIcon,
  UsersIcon
} from '@heroicons/react/24/outline';
import { useAuth } from '../contexts/AuthContext';

const Home: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();

  const features = [
    {
      icon: SparklesIcon,
      title: 'AI-Powered Challenges',
      description: 'Dynamic challenges generated by AI that adapt to your skill level and learning pace.'
    },
    {
      icon: AcademicCapIcon,
      title: 'Personalized Learning',
      description: 'Tailored learning paths based on your progress, strengths, and areas for improvement.'
    },
    {
      icon: ShieldCheckIcon,
      title: 'Real-world Security',
      description: 'Practice on realistic scenarios covering web security, cryptography, and network analysis.'
    },
    {
      icon: ChartBarIcon,
      title: 'Advanced Analytics',
      description: 'Track your progress with detailed analytics and insights into your learning journey.'
    },
    {
      icon: TrophyIcon,
      title: 'Competitive Environment',
      description: 'Compete with peers on leaderboards and earn badges for your achievements.'
    },
    {
      icon: UsersIcon,
      title: 'Community Driven',
      description: 'Join a community of learners and educators working together to improve cybersecurity skills.'
    }
  ];

  const stats = [
    { label: 'Active Learners', value: '10,000+' },
    { label: 'Challenges Available', value: '500+' },
    { label: 'Skills Tracked', value: '50+' },
    { label: 'Success Rate', value: '85%' }
  ];

  if (user) {
    navigate('/dashboard');
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50 dark:from-dark-900 dark:to-dark-800">
      {/* Header */}
      <header className="relative">
        <nav className="flex items-center justify-between p-6 lg:px-8">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 bg-gradient-to-br from-primary-500 to-purple-600 rounded-xl flex items-center justify-center">
              <span className="text-white font-bold text-xl">Z</span>
            </div>
            <span className="text-2xl font-bold text-gradient">Zero2Hacker</span>
          </div>
          <div className="flex items-center space-x-4">
            <Link
              to="/auth/login"
              className="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors"
            >
              Sign In
            </Link>
            <Link
              to="/auth/register"
              className="btn-primary"
            >
              Get Started
            </Link>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="relative px-6 lg:px-8 py-20">
        <div className="mx-auto max-w-4xl text-center">
          <motion.h1
            className="text-5xl md:text-7xl font-bold text-gray-900 dark:text-white mb-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            Democratizing{' '}
            <span className="text-gradient">Cybersecurity</span>{' '}
            Education
          </motion.h1>

          <motion.p
            className="text-xl md:text-2xl text-gray-600 dark:text-gray-300 mb-8 max-w-3xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            Learn cybersecurity through AI-personalized CTF challenges that adapt to your skill level
            and guide you from zero to hacker.
          </motion.p>

          <motion.div
            className="flex flex-col sm:flex-row gap-4 justify-center items-center"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            <Link
              to="/auth/register"
              className="btn-primary text-lg px-8 py-4 w-full sm:w-auto"
            >
              Start Learning Free
            </Link>
            <Link
              to="/auth/login"
              className="btn-outline text-lg px-8 py-4 w-full sm:w-auto"
            >
              Sign In
            </Link>
          </motion.div>
        </div>

        {/* Hero Image/Demo */}
        <motion.div
          className="mt-16 relative mx-auto max-w-5xl"
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.6 }}
        >
          <div className="rounded-2xl overflow-hidden shadow-2xl bg-white dark:bg-dark-800 border border-gray-200 dark:border-dark-700">
            <div className="p-6">
              <div className="flex items-center space-x-2 mb-4">
                <div className="w-3 h-3 bg-red-500 rounded-full"></div>
                <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                <div className="w-3 h-3 bg-green-500 rounded-full"></div>
              </div>
              <div className="bg-dark-900 rounded-lg p-6 font-mono text-sm">
                <div className="text-green-400">
                  <span className="text-gray-500">$</span> nc challenge.zero2hacker.com 8080
                </div>
                <div className="text-white mt-2">
                  Welcome to Zero2Hacker CTF Platform!<br />
                  <span className="text-blue-400">Challenge:</span> Find the hidden flag in this SQL injection vulnerability<br />
                  <span className="text-yellow-400">Hint:</span> Try common SQL injection payloads...<br />
                  <span className="text-green-400">Flag:</span> flag&#123;sql_injection_mastery&#125;
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* Stats Section */}
      <section className="py-16 bg-white dark:bg-dark-800 border-y border-gray-200 dark:border-dark-700">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, index) => (
              <motion.div
                key={stat.label}
                className="text-center"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <div className="text-3xl lg:text-4xl font-bold text-primary-600 dark:text-primary-400">
                  {stat.value}
                </div>
                <div className="text-gray-600 dark:text-gray-400 mt-2">
                  {stat.label}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="text-center mb-16">
            <motion.h2
              className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-4"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              Why Choose Zero2Hacker?
            </motion.h2>
            <motion.p
              className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              Our AI-driven platform provides a personalized learning experience that adapts to your pace and skill level.
            </motion.p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                className="card hover:shadow-lg transition-shadow duration-300"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                whileHover={{ y: -5 }}
              >
                <div className="flex items-center space-x-4 mb-4">
                  <div className="p-3 bg-primary-100 dark:bg-primary-900 rounded-lg">
                    <feature.icon className="h-6 w-6 text-primary-600 dark:text-primary-400" />
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white">
                    {feature.title}
                  </h3>
                </div>
                <p className="text-gray-600 dark:text-gray-300">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-primary-600 to-purple-600">
        <div className="max-w-4xl mx-auto text-center px-6 lg:px-8">
          <motion.h2
            className="text-4xl md:text-5xl font-bold text-white mb-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            Ready to Start Your Cybersecurity Journey?
          </motion.h2>
          <motion.p
            className="text-xl text-blue-100 mb-8"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            Join thousands of learners who are building their cybersecurity skills with our AI-powered platform.
          </motion.p>
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.4 }}
          >
            <Link
              to="/auth/register"
              className="btn-secondary bg-white text-primary-600 hover:bg-gray-100 text-lg px-8 py-4"
            >
              Get Started for Free
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-dark-900 text-white py-12">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div className="col-span-1 md:col-span-2">
              <div className="flex items-center space-x-3 mb-4">
                <div className="w-8 h-8 bg-gradient-to-br from-primary-500 to-purple-600 rounded-lg flex items-center justify-center">
                  <span className="text-white font-bold text-lg">Z</span>
                </div>
                <span className="text-xl font-bold">Zero2Hacker</span>
              </div>
              <p className="text-gray-300 mb-4">
                Democratizing cybersecurity education through AI-personalized CTF challenges.
              </p>
              <p className="text-gray-400 text-sm">
                © 2024 Zero2Hacker. All rights reserved.
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Platform</h3>
              <ul className="space-y-2 text-gray-300">
                <li><a href="/challenges" className="hover:text-white transition-colors">Challenges</a></li>
                <li><a href="/dashboard" className="hover:text-white transition-colors">Learning Paths</a></li>
                <li><a href="/leaderboard" className="hover:text-white transition-colors">Leaderboard</a></li>
                <li><a href="/analytics" className="hover:text-white transition-colors">Analytics</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Support</h3>
              <ul className="space-y-2 text-gray-300">
                <li><a href="/dashboard" className="hover:text-white transition-colors">Documentation</a></li>
                <li><a href="/dashboard" className="hover:text-white transition-colors">Community</a></li>
                <li><a href="/dashboard" className="hover:text-white transition-colors">Contact</a></li>
                <li><a href="/dashboard" className="hover:text-white transition-colors">Privacy</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;